export const FILL_FORM = "FILL_FORM";
export const RESET_FORM = "RESET_FORM";
export const CHOOSE_SHIPMENT = "CHOOSE_SHIPMENT";
export const CHOOSE_PAYMENT = "CHOOSE_PAYMENT";
export const CHECK_DROPSHIP = "CHECK_DROPSHIP";
export const SET_BUTTON = "SET_BUTTON"; 
export const GENERATE_ORDER_ID = "GENERATE_ORDER_ID"; 
